### ISSUE TITLE
Make a suggestion 

### ISSUE THREAD

**Issue by yangyang-studio** [behrouzz/occultation#1]
Hello, sir 

This code link increases the phase of the moon on the day of the event, which is more intuitive 。

Thanks

**Comment by behrouzz** [comment]
Hello. I don't see any link.

**Comment by yangyang-studio** [comment]
> 你好。我没有看到任何链接。

What I mean is that you can add code, calculate the moon phase of the day and draw it

**Comment by behrouzz** [comment]
It is a very good suggestion to add the moon phase. Thanks.

**Comment by yangyang-studio** [comment]
Hello, sir&nbsp;


No need to thank, are some of their own ideas, look forward to the future can be achieved, wait and see. 🌝😃


Best wishes&nbsp;












ZY-LunarCrater
***@***.***


---Original---
From: ***@***.***&gt;
Date: Fri, Dec 23, 2022 22:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [behrouzz/occultation] Make a suggestion  (Issue #1)




 
It is a very good suggestion to add the moon phase. Thanks.
